max-party-size: 3 # maximum amount of players in a single party (valid values are: 2-9)
party-chat:
  enabled: true # if party chat is enabled
  prefix: @ # prefix character for chat messages
shared-experience: party # how to share experience (valid values are: [disabled, split, equal, party])
shared-inventory: party # how to share inventory (valid values are: [disabled, split, equal, party])
